### PR TITLE
[New Hack] 063-Intro To Azure Red Hat OpenShift WhatTheHack

### PR DESCRIPTION
**Pull request by danielkon96**

### CODE REVIEW

**Review by perktime — APPROVED** [review]
Content looks good!

**Comment by danielkon96** [comment]
> Content looks good!

One thing I just noticed is that Sowmyan's name is spelled wrong in the readme. Do I make that change or should you?

**Comment by danielkon96** [comment]
@perktime @jrzyshr Is this ready to merge? It needs approval from 1 more person.

**Comment by jrzyshr** [comment]
In /Student/Resources/Challenge-02, you have the sample app code.  Clearly this was copied "as-is" from the Microsoft Learn repository.  The README.md and others (security.md, codeofconduct.md, etc) have all the information referring to it being part of MS Learn repo.  We should probably strip that stuff out.

**Review by jrzyshr — APPROVED** [review]
Thanks team for this awesome new contribution to the WTH collection!

**Pull request merged**
