### PR TITLE
Added workaround to copy files into ADLS v2

### PR DESCRIPTION
**Pull request by danabases**
Added workaround to copy files into ADLS v2 using Storage Explorer

### CODE REVIEW

**Comment by danabases** [comment]
Added workaround to copy files into ADLS v2 using Storage Explorer

**Comment by danabases** [comment]
Hi @gfilicetti.  More info - The addition was made to Page 1, Task 1, new paragraph added after the "Note:" (line 16).  Thanks!

**Comment by gfilicetti** [comment]
Bump @plzm ... let me know if we're good to go. Thanks.

**Comment by plzm** [comment]
@gfilicetti  Good to go with Dana's PR. Please accept it.

**Comment by gfilicetti** [comment]
Thank you @danabases for your contribution.

**Pull request merged**
