### PR TITLE
Update 01-provision-b2c.md

### PR DESCRIPTION
**Pull request by timleyden**
removed last point, as the create tenant screen now allows you to create a new rg

### CODE REVIEW

**Comment by timleyden** [comment]
@DavidHoerster  please review

**Review by DavidHoerster — APPROVED** [review]
Looks good! Thank you!!

**Comment by DavidHoerster** [comment]
This change looks good. Please merge.

**Review by jrzyshr — APPROVED** [review]
Hi Tim!  Thanks for the update to the Identity WTH!

**Review by shbabylo — APPROVED** [review]
Review and approved!  Thank you for your contributions!!

**Pull request merged**
