### PR TITLE
[Hack Update] 031-DevOpsWithGitHub - Update challenge00.md to remove Atom and switch to Codespaces

### PR DESCRIPTION
**Pull request by gitstua**
Update GitHub challenge00.md to remove Atom and switch to GitHub Codespaces which has been made available free for 60 hours and will reduce friction for Students who are on more restricted corporate devices

### CODE REVIEW

**Comment by jrzyshr** [comment]
Hi @gitstua!  Thanks for the PR.  FYI, there is an earlier PR in the queue that makes some updates to this hack.  Once that one is merged, we'll review your change, but it may require a merge conflict resolution.  I will update this thread when that happens.

**Comment by Whowong** [comment]
@gitstua - We merged the changes from the other PR this morning.   There is a small conflict with this change.  Can you please resolve the merge conflict and we can then review?

**Comment by gitstua** [comment]
@jrzyshr and @Whowong - thanks for waiting whilst I got back to this...

Merge conflict is now resolved and I added a couple of missing things to the dictionary to pass the spell check (Codespaces and TextEdit)

Should be good to :shipit: now

**Review by Whowong — APPROVED** [review]

**Review by jrzyshr — APPROVED** [review]
Thanks for the updates @gitstua !

**Pull request merged**
