### PR TITLE
Updated IntrotoKubernetes lecture

### PR DESCRIPTION
**Pull request by larryclaman**
Made some edits to the introtokubernetes lecture (powerpoint):

- Edited/corrected slide 101 "How Services Work" with respect to clusterip, as the wireframe diagram was incorrect.
- Edited/corrected  slide 99 "network", which had incorrectly shown the same ip address on all pods

### CODE REVIEW

**Comment by gfilicetti** [comment]
Hey @larryclaman .... could you give us a little detail on your changes so we can zero in on them? Which slides are new? What are the slide numbers for the ones that were updated/changed? Were any slides deleted? ... thanks!

cc: @jrzyshr

**Comment by larryclaman** [comment]
@gfilicetti I put the specific slide numbers into the PR overview, but it's just changes to slides 99 & 101.  (I pulled back some other prior edits as they were specific to my customer)

**Comment by gfilicetti** [comment]
Hi @larryclaman ... thanks for clarifying. After my last customer delivery of 001 I had a bunch of Lecture.pptx clean ups to do. I've added your two changes (thank you VERY MUCH for that updated clusterIP graphic!).

My new [PR is here](https://github.com/microsoft/WhatTheHack/pull/222) if you want to go look.

Could you close this PR now since I rolled your changes into mine?

**Comment by larryclaman** [comment]
Closed... changes incorporated into #222

**Pull request closed without merging**
