### PR TITLE
IntroToAKS:  add paths A-D

### PR DESCRIPTION
**Pull request by larryclaman**
per our collaboration today.
Open/Todo:  add diagram to coaches guide.

### CODE REVIEW

**Comment by larryclaman** [comment]
@jrzyshr Just checking -- I believe I've made all the changes we discussed.  Anything else to do?

**Review by jrzyshr — CHANGES_REQUESTED** [review]
Hi Larry, 
Thanks for this set up updates that makes it easier for Coaches to choose a path for skipping C1, C2, or both.

There's one error that needs to be fixed.  On the Coach Guide TOC (/Coach/README.MD), the link to C2 is broken.  (This is because you renamed the C2 file.)  If you replicate the pattern you used in the Student guide, add a new C2 file in the Coach guide that links to Path A, B, or C.

**Comment by larryclaman** [comment]
Edits made per suggestion.

**Comment by larryclaman** [comment]
@jrzyshr -- fixes made as discussed

**Review by jrzyshr — APPROVED** [review]
Thanks Larry for fixing the C2 coach guide links!

**Pull request merged**
